### ISSUE TITLE
Site rendered in the same tab

### ISSUE THREAD

**Issue by nlok5923** [iiitv/sol#20]
IIITV Coding club link at the footer render the facebook profile of IIITV coding club in the same tab rest all links in this website renders the page in different window.

@iiitv/project-maintainers if this issue is valid i would like to work on it.

**Comment by theyashshahs** [comment]
can you be more specific

**Comment by nlok5923** [comment]
@yashshah2820 sir on clicking IIITV Coding club link in the footer the facebook profile opens in the same tab rather than opening in a new window.

**Comment by nlok5923** [comment]
@iiitv/project-maintainers i talking about this issue.
![issue1](https://user-images.githubusercontent.com/56120084/94329824-3b557680-ff73-11ea-9351-88509b6bbd62.gif)

**Comment by theyashshahs** [comment]
@nlok5923 GFI 👍

**Comment by theyashshahs** [comment]
Where do you want to navigate the user after this page then?

**Comment by nlok5923** [comment]
@yashshah2820 at the same page but in different window.

**Comment by theyashshahs** [comment]
> @yashshah2820 at the same page but in a different window.

Which window or a new tab?

**Comment by nlok5923** [comment]
@yashshah2820  new tab sir sorry

**Comment by theyashshahs** [comment]
But it won't make any sense to send the user to a new tab for this, it will be annoying 🤔, navigate the user to the GitHub org instead

**Comment by nlok5923** [comment]
@yashshah2820  okay sir i will do that so sir in new tab or in the current one.

**Comment by theyashshahs** [comment]
in the new tab for the GitHub org
