### ISSUE TITLE
heading overlapped with paragraph

### ISSUE THREAD

**Issue by nlok5923** [iiitv/sol#6]
![Screenshot (1289)](https://user-images.githubusercontent.com/56120084/91650200-81312480-ea31-11ea-85a1-2f724f7765d3.png)

Institute management portal heading inside a card overlapped with text when screen size changed.

i would like to work on this issue. also
@iiitv/project-maintainers please do let me know about this issue validity.

**Comment by aashutoshrathi** [comment]
@nlok5923 The issue seems legit to me.

**Comment by AmanRaj1608** [comment]
@nlok5923 
Add CSS in styles file instead of inline styling and use rem 
as Aashutosh sir told in #10

**Comment by nlok5923** [comment]
@AmanRaj1608 sir working on it.
