### ISSUE TITLE
Footer collapsed with above content

### ISSUE THREAD

**Issue by keshavagarwal17** [iiitv/sol#7]
![image](https://user-images.githubusercontent.com/56120769/91650778-541c5a80-eaa1-11ea-92ad-5038b613c270.png)
Footer is collapsing with above content
I would like to work on this issue.

**Comment by AmanRaj1608** [comment]
What's the screen size?

**Comment by keshavagarwal17** [comment]
sir this issue is in between 840-1090 width(almost)
![image](https://user-images.githubusercontent.com/56120769/91751714-e24c2a00-ebe2-11ea-8d8e-afb0873cde46.png)

**Comment by nlok5923** [comment]
@iiitv/project-maintainers if this issue is still open I would like to work on it.

**Comment by theyashshahs** [comment]
@nlok5923 you already have plenty of issues assigned to you, work on that please

**Comment by keshavagarwal17** [comment]
@yashshah2820 sir can i work on this issue

**Comment by theyashshahs** [comment]
@The-Keshav-Agarwal GFI 👍
