### ISSUE TITLE
No difference between active navlink and other links in mobile view

### ISSUE THREAD

**Issue by keshavagarwal17** [iiitv/sol#8]
In laptop view
![image](https://user-images.githubusercontent.com/56120769/91650855-91351c80-eaa2-11ea-99f4-0e7664267071.png)

In mobile view
![image](https://user-images.githubusercontent.com/56120769/91650848-706cc700-eaa2-11ea-8595-c670bb1d3adf.png)

In mobile view there is no difference between active menu link and other links
I would like to work on this issue.

**Comment by AmanRaj1608** [comment]
okay GFI 👍🏻

**Comment by AmanRaj1608** [comment]
@The-Keshav-Agarwal You are now assigned for two issues.

**Comment by keshavagarwal17** [comment]
@AmanRaj1608  sir I am working on this issue but i have one doubt. In the script.js file first line of code is as following.
new fullpage('#fullpage', {
  //options here
  autoScrolling:true,
  responsiveWidth: 832,
});

can u please tell me what is doing above line of code. because i made functionality that when i click on any navbar link background color of that link is changing accordingly in mobile view but problem is that  if i manually scroll down from one section to another than the background color of navbar link is not automatic changing in mobile view(when width is less than 832). and if i reduce the responsiveWidth according to my screen width in above code than all things are working fine.
for refrence 
when i was in about section
![image](https://user-images.githubusercontent.com/56120769/91874255-9e672c80-ec97-11ea-8c1a-2281d56c32ee.png)

when i manuall scroll and reach to the project section
![image](https://user-images.githubusercontent.com/56120769/91874344-bccd2800-ec97-11ea-9e39-867526ce6ba3.png)

when i reach to the project section by clicking navbar link
![image](https://user-images.githubusercontent.com/56120769/91874432-da01f680-ec97-11ea-82bd-5cd5cf7bdac0.png)

**Comment by AmanRaj1608** [comment]
We are using [fullpage](https://alvarotrigo.com/fullPage) here.

It's a SPA application so I don't think having active menu matters that much 😅

**Comment by keshavagarwal17** [comment]
sir is there any issue if i will change the value of responsiveWidth in code?

**Comment by AmanRaj1608** [comment]
> responsiveWidth: (default 0) A normal scroll (autoScrolling:false) will be used under the defined width in pixels. A class fp-responsive is added to the body tag in case the user wants to use it for their own responsive CSS. For example, if set to 900, whenever the browser's width is less than 900 the plugin will scroll like a normal site.

It may affect how the page scrolls down
